baseurl = "https://alessiofranceschi.dev"
title = "Alessio Franceschi"
theme = ["hugo-cloak-email", "hugo-coder-lt"]
languagecode = "en-us"
defaultcontentlanguage = "en"
copyright = 'Copyright Alessio Franceschi'
[author]
  name = 'Alessio Franceschi'

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Alessio Franceschi"
  info = "Software Engineer"
  description = "Alessio Franceschi's personal website"
  keywords = "blog,developer,personal"

  favicon_32 = "/image/favicon.png"
  favicon_16 = "/image/favicon.png"

  colorScheme = "light"
  hidecolorschemetoggle = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "LinkedIn"
  image = "/image/social/linkedin.svg"
  weight = 3
  url = "https://www.linkedin.com/in/alessio-franceschi/"
[[params.social]]
  name = "Github"
  image = "/image/social/github.svg"
  weight = 0
  url = "https://github.com/PandaSekh/"
[[params.social]]
  name = "RSS"
  image = "/image/social/rss.svg"
  weight = 10
  url = "http://localhost:1313/index.rss"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[permalinks]
  posts = '/blog/:slugorfilename'
[imaging]
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 70
  resampleFilter = 'CatmullRom'
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = ''
    includeFields = ''